export { default as cobblestoneImg } from '../assets/imgs/cobblestone.jpg'
export { default as diamondImg } from '../assets/imgs/diamond.png'
export { default as dirtImg } from '../assets/imgs/dirt.jpg'
export { default as grassImg } from '../assets/imgs/grass.jpg'
export { default as glassImg } from '../assets/imgs/glass.png'
export { default as leavesImg } from '../assets/imgs/leaves.jpg'
export { default as woodImg } from '../assets/imgs/wood.webp'
export { default as logImg } from '../assets/imgs/log.png'
